config/routes.rb
NerdTalkPool::Application.routes.draw do
  
  root :to =>  "proposals#index"

  resources :proposals do
    resources :comments

    member do
      get :vote_up
      get :vote_down
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :proposal
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
	has_many :comments

	def vote_up
		self.votes += 1
	end

	def vote_down
		self.votes -= 1
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :generate_cookie_hash, :set_votes_count

  def set_votes_count
   	if cookies[:votes_count].nil?
  		reset_votes_count
  	elsif cookies_has_more_than_a_week(cookies[:votes_age])
  		reset_votes_count
  	end
  end

private

  def reset_votes_count
  	cookies[:votes_count] = 0 
	cookies[:votes_age]	  = Time.now	
  end

  def cookies_has_more_than_a_week(cookie_age)
  	Time.parse(cookie_age) < Time.new.prev_week(:saturday)
  end

  def generate_cookie_hash
    cookies[:hash] = SecureRandom.base64 if cookies[:hash] == nil
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@proposal = Proposal.find(params[:proposal_id])
  	@proposal.comments << Comment.new(params[:comment].merge(:owner_hash => cookies[:hash]))

  	redirect_to @proposal
  end

  def destroy
  	@comment = Comment.find(params[:id])
  	@comment.destroy
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  # GET /proposals
  # GET /proposals.json
  def index
    @proposals = Proposal.order("votes desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @proposals }
    end
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
    @proposal = Proposal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @proposal }
    end
  end

  # GET /proposals/new
  # GET /proposals/new.json
  def new
    @proposal = Proposal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @proposal }
    end
  end

  # GET /proposals/1/edit
  def edit
    @proposal = Proposal.find(params[:id])
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @proposal = Proposal.new(params[:proposal])

    respond_to do |format|
      if @proposal.save
        flash[:notice] = 'Proposal was successfully created.'
        format.html { redirect_to :action => :index }
        format.json { render :json => @proposal, :status => :created, :location => @proposal }
      else
        format.html { render :action => "new" }
        format.json { render :json => @proposal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /proposals/1
  # PUT /proposals/1.json
  def update
    @proposal = Proposal.find(params[:id])

    respond_to do |format|
      if @proposal.update_attributes(params[:proposal])
        format.html { redirect_to @proposal, :notice => 'Proposal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @proposal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal = Proposal.find(params[:id])
    @proposal.destroy

    respond_to do |format|
      format.html { redirect_to proposals_url }
      format.json { head :no_content }
    end
  end


  before_filter :can_user_vote_up?,   :only => [:vote_up]
  before_filter :can_user_vote_down?, :only => [:vote_down]

  def can_user_vote_up?
    render :cant_vote if cookies[:votes_count].to_i == 3
  end

  def can_user_vote_down?
    render :cant_vote if cookies[:votes_count].to_i == 0
  end

  def vote_up
    cookies[:votes_count] = cookies[:votes_count].to_i + 1

    @proposal = Proposal.find(params[:id])
    @proposal.vote_up

    @proposal.save

    render :vote
  end

  def vote_down
    cookies[:votes_count] = cookies[:votes_count].to_i - 1

    @proposal = Proposal.find(params[:id])
    @proposal.vote_down

    @proposal.save

    render :vote
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def avatar_url(user)
	    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
	    "http://gravatar.com/avatar/#{gravatar_id}.png?s=24"
	end

	def delete_comment_link(proposal, comment)
	  if comment_owner?(comment)
		  link_to "x", [proposal, comment], :confirm => 'Are you sure?', :method => :delete, :remote => true
	  end
	end

	def markdown(text)
	    options = [:hard_wrap, :filter_html, :autolink, :no_intraemphasis, :xhtml]
	    RedCloth.new(text).to_html.html_safe
	end
	
	private 
	
	def comment_owner?(comment)
	  comment.owner_hash == cookies[:hash]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/destroy.js.erb
location.reload(true)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NerdTalkPool</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container"> 
		<div class="content">

			<%= yield %>
			<hr/>
			<footer>
				<div class="center">Nerd Talk @2012</div>
			</footer>
		</div>
		
	</div>

</body>
</html>

app/views/proposals/_comment.html.erb
<%= form_for @proposal.comments.build, :url => proposal_comments_path(@proposal), :class => "form-horizontal"  do |c| -%>
	<fieldset>
		<legend>Novo Comentário:</legend>
		<div class="control-group">
			<label class="control-label">Email:</label>
			<div class="controls"> 
				
				<div class="input-prepend">
	              	<span class="add-on"><i class="icon-envelope"></i></span>
					<%= c.email_field :email, :class => "span6" %>
	            </div>
				
				
			</div>
		</div>
	
		<div class="control-group">
			<label class="control-label">Comentário:</label>
				<div class="controls">
					<%= c.text_area :content, :class => "input-xlarge span6" %> <br/>
				</div>
			</div>
			<%= c.submit "Commentar", :class => "btn" %>
		</div>
	</fieldset>	
<% end -%>

app/views/proposals/_form.html.erb
<%= form_for(@proposal) do |f| %>
  <% if @proposal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proposal.errors.count, "error") %> prohibited this proposal from being saved:</h2>

      <ul>
      <% @proposal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<fieldset id="" class="">
	  <div class="field">
	    <%= f.label :title, "Título" %><br />
	    <%= f.text_field :title, :style => "width: 100%" %>
	  </div>
	  <div class="field">
	    <%= f.label :description, "Descrição" %>
		<small class="pull-right">Formatação de texto: <a href="http://en.wikipedia.org/wiki/Textile_(markup_language)" target="_blank">Textile (Wikipedia)</small>
	    <%= f.text_area :description, :style => "width: 100%" %>
	  </div>
	  <div class="actions">
	    <%= f.submit "Adicionar ideia", :class => "btn btn-primary" %>
	  </div>
	</fieldset>
<% end %>

app/views/proposals/cant_vote.js.erb
alert("Sua cota de votos dessa semana acabou. Remova votos de outras propostas pra poder continuar a votar.")

app/views/proposals/edit.html.erb
<div class="row">
    <div class="span12">
		<div class="page-header">
			<p>
				<h3><%= link_to '<< voltar', @proposal %></h3>
			</p>
			<h1>	
				Editando Idéia: <%= @proposal.title %>
	        </h1>
		</div>


		<%= render 'form' %>

	</div>
</div>

app/views/proposals/index.html.erb
<div class="hero-unit">
  <h1>Papo Nerd!</h1>
  <p>Sugestões e comentários sobre os temas a serem apresentados pra nossa sessão de nerdisse.</p>
      <%= link_to 'Eu quero cadastrar uma Nova ideia!', new_proposal_path, :class => "btn btn-primary" %>
</div>



<div class="row">
    <div class="span12">
      <% if flash[:notice] %>
        <div class="alert-message success">
           <%= flash[:notice] %>         
          <a class="close" data-dismiss="alert">×</a>
        </div>  
      <% end -%>

      <h1>E vamos às ideias!</h1>

      

      <div id="proposals">
        <% @proposals.each do |proposal| %>
          <div id="proposal_id_<%= proposal.id %>" >
            <div class="page-header">
              <h1>
                <%= link_to proposal.title, proposal %>
                <small>
                  Votos: <span class="votes_count"><%= proposal.votes %></span> | 
                  <%= link_to 'Up',   vote_up_proposal_path(proposal),   :remote => true %>
                  <%= link_to 'Down', vote_down_proposal_path(proposal), :remote => true %>
                </small>
              </h1>
            </div>

            <%= markdown(proposal.description) %>

            <h6 class="comments"> comentários: <%= proposal.comments.count %> </h6>  
          </div>
        <% end %>
      </div>
    </div>
</div>

app/views/proposals/new.html.erb
<div class="row">
	<div class="span12">

		<div class="page-header" id="proposal_id_<%= @proposal.id %>">
			<p>
				<h3><%= link_to '<< voltar', proposals_path %></h3>
			</p>
			<h1>	
				<h1>Nova ideia</h1>
	        </h1>
		</div>
		

		<%= render 'form' %>
	</div>
</div>

app/views/proposals/show.html.erb
<script type="text/javascript">
	$(function() {
		$('.destroy').popover()
	})
</script>

<div class="row">
	<div class="span12">
		<% if notice %>
			<div class="alert alert-success">
			  <%= notice %>         
			  <a class="close" data-dismiss="alert">×</a>
			</div>  
		<% end -%>

		<div class="page-header" id="proposal_id_<%= @proposal.id %>">
			<p>
				<h3><%= link_to '<< voltar', proposals_path %></h3>
			</p>
			<h1>	
				<%= @proposal.title %>
				<small>
		          Votos: <span class="votes_count"><%= @proposal.votes %></span> | 
		          <%= link_to 'Up',   vote_up_proposal_path(@proposal),   :remote => true %>
		          <%= link_to 'Down', vote_down_proposal_path(@proposal), :remote => true %>
		        </small>
	        </h1>
		</div>

		<%= markdown(@proposal.description) %>

		<%= link_to 'Edit', edit_proposal_path(@proposal), :class => "btn btn-warning btn-mini" %> 
		<%= link_to 'Destroy', @proposal, :confirm => 'Tem certeza que quer deletar?', :method => :delete, :class => "btn btn-danger btn-mini destroy", :data => { :content => "Lembre-se: Com grandes poderes vêm grandes responsabilidades! -Tio Ben" } %> 

	</div>
</div>
<hr/>
<div class="row">
	<div class="span6">
		<legend>Commentarios (<%= @proposal.comments.count %>):</legend>
		<% @proposal.comments.each do |comment| %>
			<p id="comment_id_<%= comment.id %>">
				<%= image_tag avatar_url(comment) %> <b><%= comment.email %></b> - <small><%= comment.created_at.strftime("%d/%m/%Y %H:%M") %></small>
				<%= delete_comment_link(@proposal, comment)  %> <br/>
				<%= comment.content %>
			</p>
		<% end -%>
	</div>
    <div class="span6 pull-right">
		<%= render "comment" %>
	</div>
</div>

app/views/proposals/vote.js.erb
$("#proposal_id_<%= @proposal.id %> .votes_count").html(<%= @proposal.votes %>)